### ISSUE TITLE
Client side classes called on server side 1.7.10

### ISSUE THREAD

**Issue by Claycorp** [Z-Doctor/BloodBaubles#4]
http://pastebin.com/D73RhPqn

Please name your jar after the mod and not "ZDoctorBB-whatever.jar" It is annoying trying to find a mod when its not named after what the mod name is. 
Also adflying github links is a douche move... Seriously need to be that greedy? Just use the built in curse options for your links as that's why the site exists. If you think you need that much money for making mods you really shouldn't be doing this.

**Comment by XZcutable** [comment]
I name them like that to ensure no name conflicts can arise, however unlikely it may be. When it comes to the mod itself, download links are accompanied by direct links, however, I didn't feel the need to when linking to the repository, because that is more for developers. I'm sorry if it inconvenienced you, but, if you don't want to spare me a few seconds of support, then you can find the repository through a quick google search.

I was aware of the issue as it translated into 1.9.4 and corrected the problem. I'm currently developing another add-on for 1.9.4, but understand that 1.7.10 is still very popular.

I will need to prepare my 1.7.10 dev environment, but, unfortunately, cannot dedicate all my time to coding as I have to go to work.

Because I'm happy you went through all that trouble (showing you really cared :) ), I will work on that asap. Tomorrow is my day off, so I'll try to work on it then.

As a side note, I have made absolutely nothing from making this mod or modding and poured in countless hours learning, teaching myself, and programming. I'm not expecting to make a living off of doing this (but that would be nice ;) ), but it is nice to be rewarded for my efforts. So far I am the only programmer, texture designer and beta tester, as well as, my own job in Real Life.

My adfly links have generated $3.89 with over 2000 people using them, while over 5000+ people have downloaded and used my mod. I try to make it very optional to support me to get the mod itself, but for little things that are not directly related to playing it, I have no qualms about adding an adfly link. I'm sorry if this upsets you. Recently I added warnings about adfly links but may have neglected

**Comment by XZcutable** [comment]
I fixed it, but my solution reduces the info seen and doesn't work as expected (due to version 1.7.10). I going to try to find a work around or maybe just remove it from servers for the time being.

**Comment by XZcutable** [comment]
I'm just going to release a version of the mod that has that feature removed, because making it work is becoming harder than I would have liked it. This version would be more for servers.
